### ISSUE TITLE
Screen 13 doesn't work with MoltenVK

### ISSUE THREAD

**Issue by PENGUINLIONG** [attackgoat/screen-13#61]
It seems the Screen 13 no longer works with MoltenVK on macOS but I found MoltenVK-related code around so I wonder if it's in progress or the things just don't work with Apple anymore?

The current implementation basically fails on imageless framebuffer: 

https://github.com/attackgoat/screen-13/blob/2c93683ba748340e78169412987579bf393484a0/src/driver/device.rs#L252-L256

**Comment by attackgoat** [comment]
There was a point where Screen 13 worked with MoltenVK, but the code has since changed to require imageless framebuffer and I haven't gotten around to fixing it yet.

I do have a Mac I can borrow, and I think I will try to figure that out. MoltenVK does support the required features in the latest version, but not the one currently delivered with `ash-molten`.

**Comment by PENGUINLIONG** [comment]
Oof. That's totally unexpected.

**Comment by attackgoat** [comment]
As an update - I followed the steps given by `ash-molten` to upgrade MoltenVK; I was able to get a few examples to run properly but some of them didn't open a window or crashed. The Mac is an M2 mini, which is totally new to me and I'll have to investigate more what can be done to get everything working.

I do believe everything *should* be fixable - this is why I have always kept the Vulkan version provided by Screen 13 locked at 1.2, knowing MoltenVK doesn't support 1.3.
